# QUICK COPY [260202]
# from rich.pretty import pprint; pprint(locals()); import ipdb; ipdb.set_trace()

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

global_vars:
  - name: SCRIPT
    type: shell
    params:
      cmd: "echo ~/.config/espanso/scripts"

  - name: my_date
    type: date
    params:
      format: "%y%m%d"

  - name: my_jp_date
    type: shell
    params:
      cmd: "python3 -c \"print('{{my_date}}'.translate(str.maketrans('0123456789', '０１２３４５６７８９')))\""

  - name: mytime
    type: date
    params:
      format: "%H:%M"

matches:

    # competitive programming
  - trigger: ":aoc"
    replace: "advent-of-code"

  # neovim
  - trigger: ":vh"
    replace: ":vert h "
  - trigger: ":lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
    force_clipboard: true
  - trigger: ":abc"
    replace: "abcdefghijklmnopqrstuvwxyz"
  - trigger: ":ABC"
    replace: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

  - trigger: ":rch"
    replace: "R.E.A.C.H."
  - trigger: ":tdrm"
    replace: "TODO remove this later"
    force_clipboard: true

  # github review
  - trigger: ":sug"
    replace: "```suggestion\n"
  - trigger: ":4 "
    replace: "    "
  - trigger: ":8 "
    replace: "        "
  - trigger: ":12 "
    replace: "            "
  - trigger: ":16 "
    replace: "                "

  # python breakpoint
  - trigger: ":bp"
    replace: "from rich.pretty import pprint as pp, pprint as print, pprint as p, install; install(); breakpoint()"
    force_clipboard: true
  # - trigger: ":pudb"
  #   replace: "import pudb; pudb.set_trace()"
  #   force_clipboard: true
  # - trigger: ":pp"
  #   replace: "from rich.pretty import pprint as pp"
  #   force_clipboard: true
  # - trigger: ":pri"
  #   replace: "from rich import pretty; pretty.install()"
  #   force_clipboard: true
  # - trigger: ":pxl"
  #   replace: "from rich.pretty import pprint as pp; pp(locals())"
  #   force_clipboard: true
  
  # common symbols
  - trigger: ":eur"
    replace: "€"
  - trigger: ":gbp"
    replace: "£"
  - trigger: ":jpy"
    replace: "¥"
  - trigger: ":sum"
    replace: "∑"
  - trigger: ":pi"
    replace: "π"
  - trigger: ":deg"
    replace: "°"
  - trigger: ":elem"
    replace: "∈"
  - trigger: ":~"
    replace: "〜"

  # math stuffs
  - trigger: ":sub0"
    replace: "₀"
  - trigger: ":sub1"
    replace: "₁"
  - trigger: ":h0"
    replace: "H₀"
  - trigger: ":h1"
    replace: "H₁"
  - trigger: ":mu"
    replace: "μ"
  - trigger: ":neq"
    replace: "≠"
  - trigger: ":barx"
    replace: "x̄"
  - trigger: ":bary"
    replace: "ȳ"
  - trigger: ":^2"
    replace: "²"

  # emojis
  - trigger: ":lenny"
    replace: "( ͡° ͜ʖ ͡°)"
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: ":flip"
    replace: "(ノ ゜Д゜)ノ ︵ ┻━┻"
  - trigger: ":unflip"
    replace: "┬─┬ノ( º _ ºノ)"
  - trigger: ":tears"
    replace: "(ಥ﹏ಥ)"
  - trigger: ":disap"
    replace: "ಠ_ಠ"
  - trigger: ":wink"
    replace: "(｡•̀ᴗ-)✧"
  - trigger: ":hide"
    replace: "┬┴┬┴┤(･_├┬┴┬┴"
  - trigger: ":cat"
    replace: "( Φ ω Φ )"
  - trigger: ":dog"
    replace: "U・ᴥ・U"
  - trigger: ":tatakae"
    replace: "(ಠ o ಠ)¤=[]:::::>"
  - trigger: ":party"
    replace: "ヾ(⌐■_■)ノ♪"
  - trigger: ":party"
    replace: "✺◟( • ω • )◞✺"
  - trigger: ":party"
    replace: "🥳"
  - trigger: ":think"
    replace: "🤔"
  - trigger: ":spark"
    replace: "✨"
  - trigger: ":ok"
    replace: "👌"
  - trigger: ":STAR"
    replace: "🌟"
  - trigger: ":salut"
    replace: "🫡"
  - trigger: ":chk"
    replace: "✅"
  - trigger: ":bchk"
    replace: "☑️"
  - trigger: ":inprg"
    replace: "🔄"
  - trigger: ":soon"
    replace: "▶️"

  # Stars script (0~5)
  # :s[0~5] prints close stars (★★★★★)
  # :ss[0~5] prints distant stars (★ ★ ★ ★ ★ )
  # :S~ / :SS~ prints on 10 stars system (ST/SST for full 10 star)
  # :-s[0~5] (or other type of s) appends "- " at the start
  - regex: ":(?P<trigger>((-|j)?((s|ss)[0-5]|(S|SS)[0-9]|ST|SST)))"
    replace: "{{output}} "
    force_clipboard: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"{{SCRIPT}}/stars.py\" {{trigger}}"

  - trigger: ":j-"
    replace: "・"

  - regex: ":ou(?P<trigger>([1-3][1-4][0-1][1-9]))"
    replace: "{{output}} "
    force_clipboard: true
    vars:
      - name: output
        type: shell
        params:
          cmd: "python3 \"{{SCRIPT}}/ou.py\" {{trigger}}"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":date"
    replace: "{{my_date}}"
  - trigger: ":sdate"
    replace: "[{{my_date}}]"
  - trigger: ":jdate"
    replace: "「{{my_date}}」"
  - trigger: ":jpdate"
    replace: "「{{my_jp_date}}」"
    force_clipboard: true

  # 251108 Print the current time
  - trigger: ":time"
    replace: "{{mytime}}"

  - trigger: ":stime"
    replace: "[{{mytime}}]"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
